spring:
  datasource:
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/sweater?serverTimezone=Europe/Moscow
    username: sweater
    password: sweater
  jpa:
    generate-ddl: false
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
  freemarker:
    expose-request-attributes: true
  mail:
    host: smtp.yandex.ru
    username: dk-st31-eventmanager@yandex.ru
    password:
    port: 465
    protocol: smtps
mail:
  debug: true

#      properties:
#        hibernate:
#          format_sql: true
#          dialect: org.hibernate.dialect.PostgreSQL10Dialect
upload-path: /media/Media/MyProjects/Projects/Sweater/uploads
